FROM node:16-alpine

# installs development toolchain & libraries in order to build the sqlite package
# on the ARM architecture 
RUN apk add --no-cache python3 py3-pip bash curl make gcc libc-dev g++
# ARM sqlite build executes "python", not "python3"
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt/ivis-remote

COPY package*.json ./
RUN npm install
RUN npm install sqlite3

COPY . /opt/ivis-remote
ENTRYPOINT [ "./setup/docker-entry.sh", "dev" ]