# TODO HTTPS??? (external proxy? - watch out for docker bypassing firewall)

FROM node:16-alpine
WORKDIR /opt/ivis-remote
COPY . /opt/ivis-remote
RUN apk add --no-cache python3 py3-pip bash
RUN npm install --legacy-peer-deps
RUN npm install sqlite3 --legacy-peer-deps
RUN . ./setup/setupIVISPck.sh
CMD ["node", "src/index.js"]
EXPOSE 3000