version: '3'
services:
  rjr-proxy:
    image: nginx
    volumes:
      - ./config/nginx/devel.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/:/opt/cert:ro
    container_name: rjr-proxy
      # in IVIS-core 9090 should be set as the executor port parameter
      # (not when running on the same docker network - in that case, you don't need to expose the port)
    ports:
      - "127.0.0.1:9088:9088" # uncomment to expose the development backdoor
      # - 9090:9443 # 9443 corresponds with the proxy setting in nginx.conf! should not be needed
    depends_on:
      - rjr
    networks:
      ivis-containerized_ivis-net:
  rjr:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./src:/opt/ivis-remote/src
      - ./data:/opt/ivis-remote/data
      - ./files:/opt/ivis-remote/files
      - ./test:/opt/ivis-remote/test
      - ./config:/opt/ivis-remote/config
      - ./cert:/opt/ivis-remote/cert
      - ./setup/jobs:/opt/ivis-remote/setup/jobs
    container_name: rjr

# attach to external network to test functionality (do not forget about the proxy)
    networks:
      ivis-containerized_ivis-net:

networks:
  ivis-containerized_ivis-net:
    external: true