version: '3'
services:
  rje:
    image: nginx
    volumes:
      - ./proxyCfg/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/:/opt/cert:ro
    container_name: rje-nginx
    # networks:
    #   ivis-containerized_ivis-net:
    ports:
      - 9088:9088
    depends_on:
      - ivis-remote-runner
  ivis-remote-runner:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./src:/opt/ivis-remote/src
      - ./data:/opt/ivis-remote/data
      - ./files:/opt/ivis-remote/files
      - ./test:/opt/ivis-remote/test
      - ./config:/opt/ivis-remote/config
      - ./cert:/opt/ivis-remote/cert
      - ./setup/jobs:/opt/ivis-remote/setup/jobs
    container_name: ivis-remote-runner

# attach to external network to test functionality
#     networks:
#       ivis-containerized_ivis-net:

# networks:
#   ivis-containerized_ivis-net:
#     external: true