version: '3'
services:
  rjr-proxy:
    image: nginx
    volumes:
      - ./proxyCfg/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/:/opt/cert:ro
    container_name: rjr-proxy
    ports:
      # in IVIS-core 9090 should be set as the executor port parameter
      - 9090:9443 # 9443 corresponds with the proxy setting in nginx.conf!
    depends_on:
      - rjr
  rjr:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./src:/opt/ivis-remote/src
      - ./data:/opt/ivis-remote/data
      - ./files:/opt/ivis-remote/files
      - ./test:/opt/ivis-remote/test
      - ./config:/opt/ivis-remote/config
      - ./cert:/opt/ivis-remote/cert
      - ./setup/jobs:/opt/ivis-remote/setup/jobs
    container_name: rjr

# attach to external network to test functionality (do not forget about the proxy)
    # networks:
    #   ivis-containerized_ivis-net:

# networks:
#   ivis-containerized_ivis-net:
#     external: true