# all paths are relative to the project root
ivisCore:
  trustedIPOrName: ivis.tapache
  # the IVIS-core port designated for remote-worker communication
  # (emulation of run-manager emitted messages to the IVIS-core)
  # (if IVIS-core supports HTTPS) communication on this port is only 
  # allowed using the worker's client certificate
  trustedAuthPort: 443
  sandboxIPOrName: sbox.tapache
  sandboxPort: 443
  # same limitations as above
  es:
    host: ivis.tapache
    port: 8446
  # use local CA when PERFORMING REQUESTS to accept a locally-issued certificate
  # e.g. when not running on the internet
  # set to false if the IVIS-core server certificate may be verified normally 
  # (using global certificate chain of trust)
  useLocalCA: true
  CACert: ./cert/ca.cert
  venvCmd: 'python3 -m venv'

jobRunner:
  # reminder: the usage of cerficiates will force HTTPS
  # and becuase of that, IVIS-core is expected to have
  # HTTPS enabled as well
  useCertificates: true
  # IVIS-core-issued server certificate
  # (used when IVIS-core sends requests to the worker)
  serverCert:
    certPath: ./cert/rjr.cert
    keyPath:  ./cert/rjr.pem
  # IVIS-core-issued client certificate
  # (used when the worker sends requests to IVIS-core)
  clientCert:
    certPath: ./cert/rjr.cert
    keyPath:  ./cert/rjr.pem
  # this one should not really change when using docker, 
  # since it is very much internal to the docker compose setup 
  port: 8080
  machineId: 0
  maxJobOutput: 1000000
  # in seconds
  workCheckInterval: 5
  printLimitReachedMessage: true
  messagePush:
    # how many times a message push will be retried in case of failure
    maxRetryCount: 0
    # in seconds
    retryInterval: 1
    pushDestination: "/rest/remote"
