ivisCore:
  hostIPOrName: 0.0.0.0
  ivisTLSPort: 8080
  ivisElasticSearchPort: 9200
  CACert: ./certs/ca.crt
  venvCmd: 'python3 -m venv'

jobRunner:
  serverCertificatePath: ./certs/srv.crt
  serverCertificateKeyPath: ./certs/srv.key
  clientCertificatePath: ./certs/client.crt
  clientCertificateKey: ./certs/client.key
  port: 443
  machineId: 0