# all paths are relative to the project root
ivisCore:
  trustedIPOrName: 0.0.0.0
  # the IVIS-core port designated for remote-worker communication
  # (emulation of run-manager emitted messages to the IVIS-core)
  # (if IVIS-core supports HTTPS) communication on this port is only 
  # allowed using the worker's client certificate
  trustedAuthPort: 9080
  sandboxIPOrName: 0.0.0.0
  # TODO: uses HTTPS client-cert or not? (reminder... tokens!)
  sandboxPort: 9081
  # same limitations as above
  es:
    host: 0.0.0.0
    port: 9200
  # use local CA when PERFORMING REQUESTS to accept a locally-issued certificate
  # e.g. when not running on the internet
  # set to false if the IVIS-core server certificate may be verified normally 
  # (using global certificate chain of trust)
  useLocalCA: true
  CACert: ./cert/ca.cert.pem
  venvCmd: 'python3 -m venv'

jobRunner:
  # reminder: the usage of cerficiates will force HTTPS
  # and becuase of that, IVIS-core is expected to have
  # HTTPS enabled as well
  useCertificates: true
  # IVIS-core-issued server certificate
  # (used when IVIS-core sends requests to the worker)
  serverCert:
    certPath: ./cert/runner.cert.pem
    keyPath:  ./cert/runner.key.insecure
  # IVIS-core-issued client certificate
  # (used when the worker sends requests to IVIS-core)
  clientCert:
    certPath: ./cert/runner.cert.pem
    keyPath:  ./cert/runner.key.insecure
  port: 443
  machineId: 0
  maxJobOutput: 1000000
  # in seconds
  workCheckInterval: 5
  printLimitReachedMessage: true
  messagePush:
    # how many times a message push will be retried in case of failure
    maxRetryCount: 2
    # in seconds
    retryInterval: 1
    pushDestination: "/rc/push"
